export const locations = [
  {
    region: "Seoul",
    city: "Gangnam-gu",
    krName: "강남구",
    latitude: 37.52,
    longitude: 127.05,
  },
  {
    region: "Seoul",
    city: "Jongno-gu",
    krName: "종로구",
    latitude: 37.57,
    longitude: 126.98,
  },
  {
    region: "Seoul",
    city: "Seocho-gu",
    krName: "서초구",
    latitude: 37.48,
    longitude: 127.03,
  },
  {
    region: "Seoul",
    city: "Songpa-gu",
    krName: "송파구",
    latitude: 37.51,
    longitude: 127.11,
  },
  {
    region: "Seoul",
    city: "Gwanak-gu",
    krName: "관악구",
    latitude: 37.48,
    longitude: 126.95,
  },
  {
    region: "Seoul",
    city: "Mapo-gu",
    krName: "마포구",
    latitude: 37.57,
    longitude: 126.9,
  },
  {
    region: "Seoul",
    city: "Jung-gu",
    krName: "중구",
    latitude: 37.56,
    longitude: 126.99,
  },
  {
    region: "Seoul",
    city: "Dobong-gu",
    krName: "도봉구",
    latitude: 37.67,
    longitude: 127.05,
  },
  {
    region: "Seoul",
    city: "Gangdong-gu",
    krName: "강동구",
    latitude: 37.53,
    longitude: 127.12,
  },
  {
    region: "Gyeonggi",
    city: "Suwon-si",
    krName: "수원",
    latitude: 37.26,
    longitude: 127.03,
  },
  {
    region: "Gyeonggi",
    city: "Seongnam-si",
    krName: "성남",
    latitude: 37.42,
    longitude: 127.13,
  },
  {
    region: "Gyeonggi",
    city: "Goyang-si",
    krName: "고양",
    latitude: 37.66,
    longitude: 126.83,
  },
  {
    region: "Gyeonggi",
    city: "Yongin",
    krName: "용인",
    latitude: 37.24,
    longitude: 127.18,
  },
  {
    region: "Gyeonggi",
    city: "Uijeongbu-si",
    krName: "의정부",
    latitude: 37.74,
    longitude: 127.03,
  },
  {
    region: "Gyeonggi",
    city: "Paju",
    krName: "파주",
    latitude: 37.76,
    longitude: 126.78,
  },
  {
    region: "Gyeonggi",
    city: "Namyangju",
    krName: "남양주",
    latitude: 37.64,
    longitude: 127.22,
  },
  {
    region: "Gyeonggi",
    city: "Bucheon-si",
    krName: "부천",
    latitude: 37.5,
    longitude: 126.77,
  },
  {
    region: "Gyeonggi",
    city: "Guri",
    krName: "구리",
    latitude: 37.6,
    longitude: 127.14,
  },
  {
    region: "Gyeonggi",
    city: "Icheon",
    krName: "이천",
    latitude: 37.28,
    longitude: 127.44,
  },
  {
    region: "Gyeonggi",
    city: "Siheung-si",
    krName: "시흥",
    latitude: 37.38,
    longitude: 126.8,
  },
];
