export const cities = [
  { name: "Suwon-si", krName: "수원", isoCode: "KR" },
  { name: "Goyang-si", krName: "고양", isoCode: "KR" },
  { name: "Yongin", krName: "용인", isoCode: "KR" },
  { name: "Seongnam-si", krName: "성남", isoCode: "KR" },
  { name: "Bucheon-si", krName: "부천", isoCode: "KR" },
  { name: "Ansan-si", krName: "안산", isoCode: "KR" },
  { name: "Anyang-si", krName: "안양", isoCode: "KR" },
  { name: "Pyeongtaek", krName: "평택", isoCode: "KR" },
  { name: "Uijeongbu-si", krName: "의정부", isoCode: "KR" },
  { name: "Gwangmyeong-si", krName: "광명", isoCode: "KR" },
  { name: "Hanam", krName: "하남", isoCode: "KR" },
  { name: "Gimpo-si", krName: "김포", isoCode: "KR" },
  { name: "Namyangju", krName: "남양주", isoCode: "KR" },
  { name: "Paju", krName: "파주", isoCode: "KR" },
  { name: "Uiwang", krName: "의왕", isoCode: "KR" },
  { name: "Siheung-si", krName: "시흥", isoCode: "KR" },
  { name: "Gunpo", krName: "군포", isoCode: "KR" },
  { name: "Anseong", krName: "안성", isoCode: "KR" },
  { name: "Pocheon-si", krName: "포천", isoCode: "KR" },
  { name: "Yangju", krName: "양주", isoCode: "KR" },
  { name: "Gangwon-do", krName: "강원도", isoCode: "KR" },
];

// locations.js
export const locations = [
  {
    region: "Seoul",
    city: "Gangnam-gu",
    krName: "강남구",
    latitude: 37.5172,
    longitude: 127.0473,
  },
  {
    region: "Seoul",
    city: "Jongno-gu",
    krName: "종로구",
    latitude: 37.5735,
    longitude: 126.979,
  },
  {
    region: "Seoul",
    city: "Seocho-gu",
    krName: "서초구",
    latitude: 37.4836,
    longitude: 127.0327,
  },
  {
    region: "Seoul",
    city: "Songpa-gu",
    krName: "송파구",
    latitude: 37.5145,
    longitude: 127.1056,
  },
  {
    region: "Seoul",
    city: "Gwanak-gu",
    krName: "관악구",
    latitude: 37.4784,
    longitude: 126.9516,
  },
  {
    region: "Seoul",
    city: "Mapo-gu",
    krName: "마포구",
    latitude: 37.5663,
    longitude: 126.9014,
  },
  {
    region: "Seoul",
    city: "Jung-gu",
    krName: "중구",
    latitude: 37.5638,
    longitude: 126.9976,
  },
  {
    region: "Seoul",
    city: "Dobong-gu",
    krName: "도봉구",
    latitude: 37.6688,
    longitude: 127.0469,
  },
  {
    region: "Seoul",
    city: "Gangdong-gu",
    krName: "강동구",
    latitude: 37.5301,
    longitude: 127.1238,
  },
  {
    region: "Gyeonggi",
    city: "Suwon-si",
    krName: "수원",
    latitude: 37.2636,
    longitude: 127.0286,
  },
  {
    region: "Gyeonggi",
    city: "Seongnam-si",
    krName: "성남",
    latitude: 37.42,
    longitude: 127.1265,
  },
  {
    region: "Gyeonggi",
    city: "Goyang-si",
    krName: "고양",
    latitude: 37.6584,
    longitude: 126.832,
  },
  {
    region: "Gyeonggi",
    city: "Yongin",
    krName: "용인",
    latitude: 37.2411,
    longitude: 127.1776,
  },
  {
    region: "Gyeonggi",
    city: "Uijeongbu-si",
    krName: "의정부",
    latitude: 37.7381,
    longitude: 127.0347,
  },
  {
    region: "Gyeonggi",
    city: "Paju",
    krName: "파주",
    latitude: 37.759,
    longitude: 126.7802,
  },
  {
    region: "Gyeonggi",
    city: "Namyangju",
    krName: "남양주",
    latitude: 37.6367,
    longitude: 127.2165,
  },
  {
    region: "Gyeonggi",
    city: "Bucheon-si",
    krName: "부천",
    latitude: 37.5034,
    longitude: 126.766,
  },
  {
    region: "Gyeonggi",
    city: "Guri",
    krName: "구리",
    latitude: 37.5985,
    longitude: 127.1394,
  },
  {
    region: "Gyeonggi",
    city: "Icheon",
    krName: "이천",
    latitude: 37.2795,
    longitude: 127.4429,
  },
  {
    region: "Gyeonggi",
    city: "Siheung-si",
    krName: "시흥",
    latitude: 37.3802,
    longitude: 126.8038,
  },
];
