export const cities = [
  { name: "Suwon", krName: "수원", isoCode: "KR" },
  { name: "Goyang-si", krName: "고양", isoCode: "KR" },
  { name: "Yongin", krName: "용인", isoCode: "KR" },
  { name: "Seongnam-si", krName: "성남", isoCode: "KR" },
  { name: "Bucheon-si", krName: "부천", isoCode: "KR" },
  { name: "Ansan-si", krName: "안산", isoCode: "KR" },
  { name: "Anyang-si", krName: "안양", isoCode: "KR" },
  { name: "Pyeongtaek", krName: "평택", isoCode: "KR" },
  { name: "Uijeongbu-si", krName: "의정부", isoCode: "KR" },
  { name: "Gwangmyeong-si", krName: "광명", isoCode: "KR" },
  { name: "Hanam", krName: "하남", isoCode: "KR" },
  { name: "Gimpo-si", krName: "김포", isoCode: "KR" },
  { name: "Namyangju", krName: "남양주", isoCode: "KR" },
  { name: "Paju", krName: "파주", isoCode: "KR" },
  { name: "Uiwang", krName: "의왕", isoCode: "KR" },
  { name: "Siheung-si", krName: "시흥", isoCode: "KR" },
  { name: "Gunpo", krName: "군포", isoCode: "KR" },
  { name: "Anseong", krName: "안성", isoCode: "KR" },
  { name: "Pocheon-si", krName: "포천", isoCode: "KR" },
  { name: "Yangju", krName: "양주", isoCode: "KR" },
  { name: "Gangwon-do", krName: "강원도", isoCode: "KR" },
];
